@push('styles')
    <style>
        .publication-page { min-height: calc(100vh - 78px); padding: 50px 20px 88px; background: linear-gradient(180deg, #edf7ef 0, #f8faf9 370px); }
        .publication-container { width: min(100%, 1180px); margin: 0 auto; }.publication-intro { max-width: 670px; margin: 0 auto 36px; text-align: center; }.publication-kicker { display: inline-flex; gap: 8px; align-items: center; padding: 8px 13px; border-radius: 999px; background: var(--green-light); color: var(--green-dark); font-size: 12px; font-weight: 800; }.publication-intro h1 { margin: 14px 0 10px; color: var(--green-dark); font: 800 clamp(2rem, 5vw, 3rem)/1.15 'Playfair Display', serif; }.publication-intro p { color: var(--muted); }
        .publication-grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 24px; }.publication-card { display: flex; flex-direction: column; overflow: hidden; border: 1px solid var(--border); border-radius: 22px; background: #fff; box-shadow: 0 13px 32px rgba(7,91,56,.08); transition: transform .25s, box-shadow .25s; }.publication-card:hover { transform: translateY(-6px); box-shadow: 0 22px 40px rgba(7,91,56,.14); }.publication-media { position: relative; height: 218px; overflow: hidden; background: linear-gradient(135deg, #d9ead7, #8ebc98); }.publication-media img { width: 100%; height: 100%; object-fit: cover; transition: transform .45s ease; }.publication-card:hover .publication-media img { transform: scale(1.06); }.publication-placeholder { display: grid; height: 100%; place-items: center; color: var(--green-dark); font-size: 32px; }.publication-card-body { display: flex; flex: 1; flex-direction: column; padding: 20px; }.publication-meta { margin-bottom: 9px; color: var(--green); font-size: 11px; font-weight: 800; letter-spacing: .025em; text-transform: uppercase; }.publication-card h2 { margin-bottom: 10px; color: var(--green-dark); font-size: 1.08rem; line-height: 1.38; }.publication-excerpt { flex: 1; margin-bottom: 18px; color: var(--muted); font-size: 13px; line-height: 1.65; }.publication-read { color: var(--green-dark); font-size: 13px; font-weight: 800; }.publication-read i { margin-left: 4px; transition: transform .2s; }.publication-card:hover .publication-read i { transform: translateX(3px); }
        .gallery-grid { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 18px; }.gallery-card { overflow: hidden; border: 1px solid var(--border); border-radius: 18px; background: #fff; box-shadow: 0 10px 25px rgba(7,91,56,.07); transition: transform .25s, box-shadow .25s; }.gallery-card:hover { transform: translateY(-5px); box-shadow: 0 19px 36px rgba(7,91,56,.13); }.gallery-card .publication-media { height: 170px; }.gallery-card-body { padding: 14px; }.gallery-card h2 { margin: 4px 0 7px; color: var(--green-dark); font-size: 14px; line-height: 1.35; }.gallery-date { color: var(--muted); font-size: 11px; }.publication-empty { grid-column: 1 / -1; padding: 58px 20px; border: 1px dashed #bad7c1; border-radius: 22px; color: var(--muted); background: rgba(255,255,255,.65); text-align: center; }.publication-empty i { display: block; margin-bottom: 12px; color: var(--green); font-size: 28px; }
        .publication-pagination { margin-top: 38px; }.publication-pagination nav { display: flex; justify-content: center; }.publication-pagination nav > div:first-child { display: none; }.publication-pagination nav > div:last-child { display: flex; gap: 4px; align-items: center; }.publication-pagination nav span, .publication-pagination nav a { display: inline-flex; min-width: 36px; min-height: 36px; align-items: center; justify-content: center; border: 1px solid var(--border); border-radius: 10px; background: #fff; color: var(--green-dark); font-size: 13px; }.publication-pagination nav span[aria-current="page"] > span { border-color: var(--green); background: var(--green); color: #fff; }.publication-pagination nav a:hover { background: var(--green-light); }
        .article-shell { width: min(100%, 820px); margin: 0 auto; }.article-back { display: inline-flex; align-items: center; gap: 8px; margin-bottom: 22px; color: var(--green-dark); font-size: 13px; font-weight: 800; }.article-back:hover { color: var(--green); }.article-card { overflow: hidden; border: 1px solid var(--border); border-radius: 24px; background: #fff; box-shadow: 0 18px 45px rgba(7,91,56,.1); }.article-card .publication-media { height: min(48vw, 400px); }.article-body { padding: clamp(24px, 5vw, 48px); }.article-title { margin: 10px 0 12px; color: var(--green-dark); font: 800 clamp(1.7rem, 4vw, 2.7rem)/1.2 'Playfair Display', serif; }.article-byline { padding-bottom: 22px; margin-bottom: 25px; border-bottom: 1px solid var(--border); color: var(--muted); font-size: 13px; }.article-content { color: #3f4b43; line-height: 1.85; white-space: pre-line; }.article-content p { margin-bottom: 1em; }
        @media (max-width: 900px) { .publication-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); }.gallery-grid { grid-template-columns: repeat(3, minmax(0, 1fr)); } }
        @media (max-width: 580px) { .publication-page { padding: 32px 14px 60px; }.publication-grid, .gallery-grid { grid-template-columns: 1fr; }.publication-media, .gallery-card .publication-media { height: 210px; }.article-card { border-radius: 20px; } }
    </style>
@endpush
